version: "3.7"
services:
  freepbx:
    image: crazyquark/freepbx:latest
    ports:
      - 8080:80
      - 5060:5060
      - 5060:5060/udp
      - 5160:5160
      - 5160:5160/udp
      - 10000-10100:10000-10100/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - /etc/timezone:/etc/timezone:ro 
#      - freepbx-backup:/backup
#      - freepbx-recordings:/var/spool/asterisk/monitor
    environment: 
      - TZ=America/Mexico_City
    network_mode: "bridge"
    restart: unless-stopped