version: "3.7"
services:
  freepbx:
    image: crazyquark/freepbx:15
    ports:
      - 80:80
      - 3306:3306
      - 4569:4569
      - 5060:5060
      - 5061:5061
      - 5060:5060/udp
      - 5160:5160
      - 5161:5161
      - 5160:5160/udp
      - 18000-18030:18000-18030/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - /etc/timezone:/etc/timezone:ro 
#      - freepbx-backup:/backup
#      - freepbx-recordings:/var/spool/asterisk/monitor
    environment: 
      - TZ=America/Mexico_City
    network_mode: "host"
    restart: unless-stopped