version: '3.9'

services:

  voip:
    image: ghcr.io/izer-xyz/3cx:latest
    restart: unless-stopped
    tty: true
    tmpfs:
      - /tmp/
      - /run/
      - /run/lock
    volumes:
      - voip:/mnt/voip
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    ports:
      - "5015:5015"
      - "5060:5060"
      - "5060:5060/udp"
      - "5090:5090"
      - "5090:5090/udp"
    # Añade esta línea para usar el espacio de nombres de cgroup del host
    default-cgroupns-mode: host

volumes:
  voip:
